
image: Visual Studio 2019

clone_depth: 3

platform:
  - x64

configuration:
  - Release
  
matrix:
  fast_finish: false

init:
  - cmd: cmake --version

install:
  - git submodule update --init --recursive

before_build:
  - mkdir build
  - cd build
  - dir
  - cmake ..

build_script:
  - cmake --build . --config Release -- %MSBUILD_ARGS%

test_script:
  - ctest . -C Release
